# Generated by Django 3.2.18 on 2023-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('MARKET_BUY', 'BUY'), ('MARKET_SELL', 'SELL'), ('DIVIDEND_PAYMENT', 'DIVIDEND')], max_length=25),
        ),
    ]
